import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const _localizedValues = {
    'en': {
      'login': 'Login',
      'title': 'Cardiology Expertise',
      'description': 'Take care of your heart, your life rhythm starts here.',
      'solutions': 'Heart Health Solutions',
      'joinOurCommunity': 'Join Our Cardiology Community',
      'member': 'Become a member',
      'solution': 'Best solutions',
      'registeredSuccessfully': 'Registered Successfully',
      'signUp': 'Sign up',
      'pleaseEnterEmail': 'Please Enter E-mail',
      'email': 'Email',
      'pleaseEnterPassword': 'Please Enter Password',
      'password': 'Password',
      'alreadyHaveAccount': 'Already have an account? Login',
      'name': 'Name',
      'Name': 'Name',
      'prenom': 'First name',
      'sinscrire': 'Sign up',
      'seconnecter': 'Log in',
      'pleaseEnterConfirmationPassword':
          'Please enter the confirmation password',
      'confirmPassword': 'Confirm Password',
      'passwordMatch': 'Passwords do not match',
      'phoneNumber': 'Phone Number',
      'birthDate': 'Birth Date',
      'gender': 'Gender',
      'address': 'Address',
      'profession': 'Profession',
      'saveInfo': 'Save Information',
      'pleasePhoneNumber': 'Please enter phone number',
      'pleaseBirthDate': 'Please enter birth date',
      'pleaseGender': 'Please enter gender',
      'pleaseAddress': 'Please enter address',
      'pleaseProfession': 'Please enter profession',
      'passwordsDoNotMatch': 'Passwords do not match',
      'emailAlreadyUse':
          'The email address is already in use by another account',
      'additionalInfo': 'Additional Information',
      'male': 'Male',
      'female': 'Female',
      'alreadyHaveAnAccount': 'Already have an account? Login',
      'passwordWeak': 'Password is too weak',
      'invalidEmailFormat': 'Invalid email format',
      'tryAgain': "Please try again",
      'Your_id_is_not_correct': 'Your id is not correct',
      'Your_secret_code_is_not_correct': 'Your secret code is not correct',
      'Please_Enter_secret_code': 'Please Enter secret code',
      'ADMIN_PANEL': 'ADMIN PANEL',
      'Continue': 'Continue',
      'Anthropometric_Information': 'Anthropometric Information',
      'Cancel': 'Cancel',
      'Lesson': 'Lesson',
      'Step_1': 'Step 1',
      'Please_enter': 'Please enter',
      'Step_2': 'Step 2',
      'No_previous_records_found.': 'No previous records found.',
      'Anthropometric_information_saved_successfully':
          'Anthropometric information saved successfully',
      'Error_saving_anthropometric_information':
          'Error saving anthropometric information',
      'Error_saving_anthropometric_information:':
          'Error saving anthropometric information:',
      'Error_fetching_anthropometric_data:':
          'Error fetching anthropometric data:',
      'Password_reset_email_sent_to': 'Password reset email sent to',
      'Change_Password': 'Change Password',
      'Recover_Password': 'Recover Password',
      'Password_Reset_Email_has_been_sent_!':
          'Password Reset Email has been sent !',
      'No_user_found_for_that_email.': 'No user found for that email.',
      'Password_Recovery': 'Password Recovery',
      'Enter_your_mail': 'Enter your mail',
      'Please_Enter_Email': 'Please Enter Email',
      'Send_Email': 'Send Email',
      "Don't_have_an_account?": "Don't have an account?",
      'Create': 'Create',
      'User_Logged_In_Successfully': 'User Logged In Successfully',
      'No_User_Found_for_that_Email': 'No User Found for that Email',
      'Wrong_Password_Provided_by_User': 'Wrong Password Provided by User',
      'Email_or_Password_is_Incorrect': 'Email or Password is Incorrect',
      'Please_Enter_Password': 'Please Enter Password',
      "Don't_have_an_account?_Sign_up": "Don't have an account? Sign up",
      'receive_lesson_info': 'receive lesson info',
      'Diagnosis_Results': 'Diagnosis Results',
      'Level_of_Gravity:': 'Level of Gravity:',
      'Advices': 'Advices',
      'Recommendation': 'Recommendation',
      'Close': 'Close',
      'Verify Phone Number': 'Verify Phone Number',
    },
    'fr': {
      'login': 'Connexion',
      'title': 'Expertise en Cardiologie',
      'description':
          'Prenez soin de votre cœur, votre rythme de vie commence ici.',
      'solutions': 'Solutions pour la Santé Cardiaque',
      'joinOurCommunity': 'Rejoignez notre communauté de cardiologie',
      'member': 'Devenir membre',
      'solution': 'Meilleures solutions',
      'registeredSuccessfully': 'Enregistré avec succès',
      'signUp': 'S\'inscrire',
      'pleaseEnterEmail': 'Veuillez saisir l\'e-mail',
      'email': 'E-mail',
      'pleaseEnterPassword': 'Veuillez saisir le mot de passe',
      'password': 'Mot de passe',
      'alreadyHaveAccount': 'Vous avez déjà un compte ? Connexion',
      'name': 'Nom',
      'Name': 'Nom',
      'prenom': 'Prénom',
      'sinscrire': "S'inscrire",
      'seconnecter': 'Se connecter',
      'pleaseEnterConfirmationPassword':
          'Veuillez entrer le mot de passe de confirmation',
      'confirmPassword': 'Confirmer mot de passe',
      'passwordMatch': 'Les mots de passe ne correspondent pas',
      'phoneNumber': 'Numéro de téléphone',
      'birthDate': 'Date de naissance',
      'gender': 'Genre',
      'address': 'Adresse',
      'profession': 'Profession',
      'saveInfo': 'Sauvegarder les informations',
      'pleasePhoneNumber': 'Veuillez entrer le numéro de téléphone',
      'pleaseBirthDate': 'Veuillez entrer la date de naissance',
      'pleaseGender': 'Veuillez entrer le genre',
      'pleaseAddress': 'Veuillez entrer l\'adresse',
      'pleaseProfession': 'Veuillez entrer la profession',
      'passwordsDoNotMatch': 'Les mots de passe ne correspondent pas',
      'emailAlreadyUse':
          'L\'adresse e-mail est déjà utilisée par un autre compte',
      'additionalInfo': 'Informations supplémentaires',
      'male': 'Homme',
      'female': 'Femme',
      'alreadyHaveAnAccount': 'Vous avez déjà un compte ? Connexion',
      'passwordWeak': 'Le mot de passe est trop faible',
      'invalidEmailFormat': 'Format d\'email invalide',
      'tryAgain': "Veuillez réessayer",
      'Your_id_is_not_correct': 'Votre identifiant n\'est pas correct',
      'Your_secret_code_is_not_correct': 'Votre code secret n\'est pas correct',
      'Please_Enter_secret_code': 'Veuillez entrer le code secret',
      'ADMIN_PANEL': 'PANEL ADMIN',
      'Continue': 'Continuer',
      'Anthropometric_Information': 'Informations anthropométriques',
      'Cancel': 'Annuler',
      'Lesson': 'Leçon',
      'Step_1': 'Étape 1',
      'Please_enter': 'Veuillez entrer',
      'Step_2': 'Étape 2',
      'No_previous_records_found.': 'Aucun enregistrement précédent trouvé.',
      'Anthropometric_information_saved_successfully':
          'Informations anthropométriques enregistrées avec succès',
      'Error_saving_anthropometric_information':
          'Erreur lors de l\'enregistrement des informations anthropométriques',
      'Error_saving_anthropometric_information:':
          'Erreur lors de l\'enregistrement des informations anthropométriques :',
      'Error_fetching_anthropometric_data:':
          'Erreur lors de la récupération des données anthropométriques :',
      'Password_reset_email_sent_to':
          'E-mail de réinitialisation du mot de passe envoyé à',
      'Change_Password': 'Changer le mot de passe',
      'Recover_Password': 'Récupérer le mot de passe',
      'Password_Reset_Email_has_been_sent_!':
          'L\'e-mail de réinitialisation du mot de passe a été envoyé !',
      'No_user_found_for_that_email.':
          'Aucun utilisateur trouvé pour cet e-mail.',
      'Password_Recovery': 'Récupération de mot de passe',
      'Enter_your_mail': 'Entrez votre courriel',
      'Please_Enter_Email': 'Veuillez entrer votre adresse e-mail',
      'Send_Email': 'Envoyer un email',
      "Don't_have_an_account?": "Vous n'avez pas de compte ?",
      'Create': 'Créer',
      'User_Logged_In_Successfully': 'Utilisateur connecté avec succès',
      'No_User_Found_for_that_Email':
          'Aucun utilisateur trouvé pour cet e-mail',
      'Wrong_Password_Provided_by_User':
          'Mot de passe incorrect fourni par l\'utilisateur',
      'Email_or_Password_is_Incorrect':
          'L\'e-mail ou le mot de passe est incorrect',
      'Please_Enter_Password': 'Veuillez entrer le mot de passe',
      "Don't_have_an_account?_Sign_up":
          "Vous n'avez pas de compte ? Inscrivez-vous",
      'receive_lesson_info': 'recevoir des informations sur la leçon',
      'Diagnosis_Results': 'Résultats du diagnostic',
      'Level_of_Gravity:': 'Niveau de gravité :',
      'Advices': 'Conseils',
      'Recommendation': 'Recommandation',
      'Close': 'Fermer',
      'Verify Phone Number': 'Vérifier le numéro de téléphone',
    },
    'es': {
      'login': 'Iniciar sesión',
      'title': 'Especialización en Cardiología',
      'description': 'Cuida tu corazón, tu ritmo de vida comienza aquí.',
      'solutions': 'Soluciones para la Salud del Corazón',
      'joinOurCommunity': 'Únete a nuestra comunidad de cardiología',
      'member': 'Hacerse miembro',
      'solution': 'Mejores soluciones',
      'registeredSuccessfully': 'Registrado exitosamente',
      'signUp': 'Registrarse',
      'pleaseEnterEmail': 'Por favor, ingrese el correo electrónico',
      'email': 'Correo electrónico',
      'pleaseEnterPassword': 'Por favor, ingrese la contraseña',
      'password': 'Contraseña',
      'alreadyHaveAccount': '¿Ya tienes una cuenta? Iniciar sesión',
      'nom': 'Nombre',
      'prenom': 'Nombre de pila',
      'sinscrire': 'Registrarse',
      'seconnecter': 'Iniciar sesión',
      'pleaseEnterConfirmationPassword':
          'Por favor ingresa la contraseña de confirmación',
      'confirmPassword': 'Confirmar contraseña',
      'passwordMatch': 'Las contraseñas no coinciden',
      'phoneNumber': 'Número de teléfono',
      'birthDate': 'Fecha de nacimiento',
      'gender': 'Género',
      'address': 'Dirección',
      'profession': 'Profesión',
      'saveInfo': 'Guardar información',
      'pleasePhoneNumber': 'Por favor, ingrese el número de teléfono',
      'pleaseBirthDate': 'Por favor, ingrese la fecha de nacimiento',
      'pleaseGender': 'Por favor, ingrese el género',
      'pleaseAddress': 'Por favor, ingrese la dirección',
      'pleaseProfession': 'Por favor, ingrese la profesión',
      'passwordsDoNotMatch': 'Las contraseñas no coinciden',
      'emailAlreadyUse':
          'La dirección de correo electrónico ya está en uso por otra cuenta',
      'additionalInfo': 'Información adicional',
      'male': 'Hombre',
      'female': 'Mujer',
      'alreadyHaveAnAccount': '¿Ya tienes una cuenta? Iniciar sesión',
      'passwordWeak': 'La contraseña es demasiado débil',
      'invalidEmailFormat': 'Formato de correo electrónico no válido',
      "tryAgain": "Por favor, inténtelo de nuevo",
      'Your_id_is_not_correct': 'Tu ID no es correcto',
      'Your_secret_code_is_not_correct': 'Tu código secreto no es correcto',
      'Please_Enter_secret_code': 'Por favor, introduce el código secreto',
      'ADMIN_PANEL': 'PANEL DE ADMINISTRACIÓN',
      'Continue': 'Continuar',
      'Anthropometric_Information': 'Información Antropométrica',
      'Cancel': 'Cancelar',
      'Lesson': 'Lección',
      'Step_1': 'Paso 1',
      'Please_enter': 'Por favor ingrese',
      'Step_2': 'Paso 2',
      'No_previous_records_found.': 'No se encontraron registros previos.',
      'Anthropometric_information_saved_successfully':
          'Información antropométrica guardada con éxito',
      'Error_saving_anthropometric_information':
          'Error al guardar la información antropométrica',
      'Error_saving_anthropometric_information:':
          'Error al guardar la información antropométrica:',
      'Error_fetching_anthropometric_data:':
          'Error al obtener datos antropométricos:',
      'Password_reset_email_sent_to':
          'Correo electrónico de restablecimiento de contraseña enviado a',
      'Change_Password': 'Cambiar contraseña',
      'Recover_Password': 'Recuperar contraseña',
      'Password_Reset_Email_has_been_sent_!':
          '¡El correo electrónico de restablecimiento de contraseña ha sido enviado!',
      'No_user_found_for_that_email.':
          'No se encontró ningún usuario con ese correo electrónico.',
      'Password_Recovery': 'Recuperación de contraseña',
      'Enter_your_mail': 'Ingrese su correo electrónico',
      'Please_Enter_Email': 'Por favor ingrese su correo electrónico',
      'Send_Email': 'Enviar correo electrónico',
      "Don't_have_an_account?": "¿No tienes una cuenta?",
      'Create': 'Crear',
      'User_Logged_In_Successfully': 'Usuario conectado exitosamente',
      'No_User_Found_for_that_Email':
          'No se encontró usuario para ese correo electrónico',
      'Wrong_Password_Provided_by_User':
          'Contraseña incorrecta proporcionada por el usuario',
      'Email_or_Password_is_Incorrect':
          'El correo electrónico o la contraseña son incorrectos',
      'Please_Enter_Password': 'Por favor, ingrese la contraseña',
      "Don't_have_an_account?_Sign_up": "¿No tienes una cuenta? Regístrate",
      'receive_lesson_info': 'recibir información de la lección',
      'Diagnosis_Results': 'Resultados del diagnóstico',
      'Level_of_Gravity:': 'Nivel de gravedad:',
      'Advices': 'Consejos',
      'Recommendation': 'Recomendación',
      'Close': 'Cerrar',
      'Verify Phone Number': 'Verificar número de teléfono',
    },
    'yo': {
      'login': 'Lọgọ inu',
      'title': 'Àgbélẹ̀ ìtóbi omi ìjìnlẹ̀',
      'description': 'Jí ẹrọ ẹrọ rẹ, èdá èrò ẹ̀rẹ̀ rẹ ṣe náà lórí.',
      'solutions': 'Àwọn ìlànà fún ìròyìn ìlẹ̀ ọkàn',
      'joinOurCommunity': 'Kọja lati jẹ aṣọ wa ìjìnlẹ̀',
      'member': 'Fẹ́ẹ́rẹ́ àgbélẹ̀',
      'solution': 'Àwọn ìlànà tó tóbi',
      'registeredSuccessfully': 'Tẹ aṣẹdá',
      'signUp': 'Sígn Up',
      'pleaseEnterEmail': 'Jọwọ ṣiṣẹ́ i-méélì',
      'email': 'I-méélì',
      'pleaseEnterPassword': 'Jọwọ ṣiṣẹ́ ọrọ ìfẹ́',
      'password': 'Ọrọ ìfẹ́',
      'alreadyHaveAccount': 'Ẹ ṣe pọsẹsẹ ara wa ni? Ọdẹdẹ wá',
      'name': 'Orúkọ',
      'Name': 'Orúkọ',
      'prenom': 'Orúkọ àbíkú',
      'sinscrire': 'Dabọ',
      'seconnecter': 'Lọgọ inu',
      'pleaseEnterConfirmationPassword': 'Jọwọ wọle iwe ìgbẹkẹle àṣẹ rẹ',
      'confirmPassword': 'Faṣẹ Àṣẹ',
      'passwordMatch': 'Àṣẹ kò wà ló rẹ',
      'phoneNumber': 'Nọmba foonu',
      'birthDate': 'Ọjọ ọmọde',
      'gender': 'Gẹnà',
      'address': 'Adirẹsi',
      'profession': 'Iṣẹlẹ',
      'saveInfo': 'Fẹran alaye',
      'pleasePhoneNumber': 'Jọwọ rọ nọmba foonu',
      'pleaseBirthDate': 'Jọwọ rọ ọjọ ọmọde',
      'pleaseGender': 'Jọwọ rọ gẹnà',
      'pleaseAddress': 'Jọwọ rọ adirẹsi',
      'pleaseProfession': 'Jọwọ rọ iṣẹlẹ',
      'passwordsDoNotMatch': 'Ọfẹfẹ àkọlé àgbá',
      'emailAlreadyUse': 'Imeeli ti wa ni o wa ni ohun akoko ni ile-ẹsẹ rẹ',
      'additionalInfo': 'Aṣayan tobi',
      'male': 'Okunrin',
      'female': 'Obinrin',
      'alreadyHaveAnAccount': 'Ẹ ṣe pọsẹsẹ ara wa ni? Ọdẹdẹ wá',
      'passwordWeak': 'Aṣẹ dẹ́kẹ́',
      "invalidEmailFormat": "Fọmati imeeli ti o dara julọ",
      'tryAgain': "Jẹ́ kí o ṣe irọlẹ̀ nínu",
      'Your_id_is_not_correct': 'Id rẹ ko daradara',
      'Your_secret_code_is_not_correct': 'Koodu rẹ ti ko daradara',
      'Please_Enter_secret_code': 'Jọwọ ṣe owo agbara sọrọ',
      'ADMIN_PANEL': 'PẸLU PANEL',
      'Continue': 'Tomi',
      'Anthropometric_Information': 'Alaye Anthropometric',
      'Cancel': 'Fagun',
      'Lesson': 'Ọjọọ',
      'Step_1': 'Opin 1',
      'Please_enter': 'Jọwọ rọ',
      'Step_2': 'Opin 2',
      'No_previous_records_found.': 'Kò sí awọn iwe kika',
      'Anthropometric_information_saved_successfully':
          'Alaye Anthropometric ti a ṣafiku laarin iyọnu',
      'Error_saving_anthropometric_information': 'Error lilo alaye alaye',
      'Error_saving_anthropometric_information:': 'Error lilo alaye alaye:',
      'Error_fetching_anthropometric_data:': 'Error nla ni oke itumọ alaye:',
      'Password_reset_email_sent_to': 'Imeeli iroyin itanna imulo ti o ṣe',
      'Change_Password': 'Oko iroyin',
      'Recover_Password': 'Gba iroyin',
      'Password_Reset_Email_has_been_sent_!':
          'Imeeli itanna iroyin ti o wa ṣe!',
      'No_user_found_for_that_email.': 'Kò sí olumulo tẹlẹ fun imeeli yii',
      'Password_Recovery': 'Iroyin Iroyin',
      'Enter_your_mail': 'Wọle imeeli rẹ',
      'Please_Enter_Email': 'Jọwọ ṣe imulo imeeli rẹ',
      'Send_Email': 'Fọ imeli',
      "Don't_have_an_account?": "Ṣe o ko ni akaọnti?",
      'Create': 'Ṣẹda',
      'User_Logged_In_Successfully': 'Olumulo ti a ṣafikun',
      'No_User_Found_for_that_Email': 'Kò sí olumulo tẹlẹ fun imeeli yii',
      'Wrong_Password_Provided_by_User': 'Ẹrọ ti o fi iwakọ lọ ni iyọnu',
      'Email_or_Password_is_Incorrect': 'Imeeli tabi iwakọ ko daradara',
      'Please_Enter_Password': 'Jọwọ ṣe iwakọ rẹ',
      "Don't_have_an_account?_Sign_up": "Ṣe o ko ni akaọnti? Daa si",
      'receive_lesson_info': 'gba imulo leẹkansi',
      'Diagnosis_Results': 'Ipo Ìdárayá',
      'Level_of_Gravity:': 'Ona ti Grávítì:',
      'Advices': 'Àlọfà',
      'Recommendation': 'Àyẹyẹ',
      'Close': 'Dakẹ',
      'Verify Phone Number': 'Ṣe iṣẹlẹ nọmba foonu',
    },
    'fon': {
      'login': 'Gba sọ',
      'title': 'Ganmé tɔgan yi do akpakpa',
      'description': 'Kpɔsi aɖo aɖo gbe, aɖo amɛ aɖo hɛlɛ ɖo zɔ',
      'solutions': 'Ganmé afe ɖo dɔ',
      'joinOurCommunity': 'Fɔ yɔ fɔ ɖo akpakpa',
      'member': 'Ganmé tɔgan',
      'solution': 'Afe aɖo tɔgan',
      'registeredSuccessfully': 'Tɔn fidɔ',
      'signUp': 'Sɔnɔn',
      'pleaseEnterEmail': 'Tɔn dɛ ɛ-mail',
      'email': 'Ɛ-mail',
      'pleaseEnterPassword': 'Tɔn dɛ tɔn',
      'password': 'Tɔn',
      'alreadyHaveAccount': 'Ɖo xɔ nɔ? Ɔtɔn Ɩɔxɛ',
      'name': 'Tò',
      'Name': 'Tò',
      'prenom': 'Tò àdúrà',
      'sinscrire': 'Hù',
      'seconnecter': 'Gba sọ',
      'pleaseEnterConfirmationPassword': 'Kpòn dèkè mí ló fò pàsswɔdù kɔnfirmé',
      'confirmPassword': 'Kɔnfirmé pàsswɔdù',
      'passwordMatch': 'Pàsswɔdù kòn tònú',
      'phoneNumber': 'Nɔmɛrò fònù',
      'birthDate': 'Djì djì zàn',
      'gender': 'Xexu',
      'address': 'Ase',
      'profession': 'Pɔn',
      'saveInfo': 'Gba alafọnun',
      'pleasePhoneNumber': 'Kíndẹ wa tɔmɛwònun',
      'pleaseBirthDate': 'Kíndẹ wa Ɛganmimù',
      'pleaseGender': 'Kíndẹ wa xexu',
      'pleaseAddress': 'Kíndẹ wa ase',
      'pleaseProfession': 'Kíndẹ wa pɔn',
      'passwordsDoNotMatch': 'Agbè gè àfẹfẹ',
      'emailAlreadyUse': 'Imẹ́lì to wa wáyé tó jẹ ẹkọ rẹ tó wá láti ọwọ́ kan',
      'additionalInfo': 'Xwɛkɛ tòn',
      'male': 'Sunou',
      'female': 'yonun',
      'alreadyHaveAnAccount': 'Ɔtɔn nɔ? Ɔtɔn Ɩɔxɛ',
      'passwordWeak': 'Pàsswɔdù kòn tònú',
      'invalidEmailFormat': "Fomat adreso eléktrɔniko ki bɔn",
      'tryAgain': 'Benin ko nye ena o',
      'Your_id_is_not_correct': 'Yɔ id yɛ kpɔkpɔ',
      'Your_secret_code_is_not_correct': 'Yɔ ɔkɔɔ sɛkɛt kɔd yɛ kpɔkpɔ',
      'Please_Enter_secret_code': 'Meɖe afe do dze',
      'Quiz_Result': 'Yovo tɔgban',
      'You_scored': 'To Yovo',
      'Play_Again': 'Agbɔ',
      'Settings': 'Atɔntɔ',
      'Account': 'Mɔmɔɖon',
      'Notifications': 'Notifikasiyo',
      'Privacy': 'Fiyasise',
      'About': 'Ku',
      'Welcome_to_Quizly!': 'Yɔ tɔn Quizly !',
      'Start_Quiz': 'Tɔn Yovo',
      'Error': 'Bib',
      'Terms_and_Condition': 'Kontre aɖana nusukɔsi',
      'Verify_Phone_Number': 'Bɔ e Wɛɖu-nu-tɔ',
      'Change_Password': 'Sɔtɔɖo efo',
      'User_Deleted_Successfully': 'Mɔmɔɖon la pɔsɔ',
      'You_have_successfully_deleted_your_account': 'Wo la pɔsɔ nɔ aɖana',
      'Delete_Account': 'Pɔsɔ mɔmɔɖon',
      'Edit_Lesson_List': 'Tɔmɛɖe Tɔmɛɖe lɛtɔn',
    },
  };

  static const fr = {
    'login': 'Connexion',
    'title': 'Expertise en Cardiologie',
    'description':
        'Prenez soin de votre cœur, votre rythme de vie commence ici.',
    'solutions': 'Solutions pour la Santé Cardiaque',
    'joinOurCommunity': 'Rejoignez notre communauté de cardiologie',
    'member': 'Devenir membre',
    'solution': 'Meilleures solutions',
    'registeredSuccessfully': 'Enregistré avec succès',
    'signUp': 'S\'inscrire',
    'pleaseEnterEmail': 'Veuillez saisir l\'e-mail',
    'email': 'E-mail',
    'pleaseEnterPassword': 'Veuillez saisir le mot de passe',
    'password': 'Mot de passe',
    'alreadyHaveAccount': 'Vous avez déjà un compte ? Connexion',
    'name': 'Nom',
    'Name': 'Nom',
    'prenom': 'Prénom',
    'sinscrire': "S'inscrire",
    'seconnecter': 'Se connecter',
    'pleaseEnterConfirmationPassword':
        'Veuillez entrer le mot de passe de confirmation',
    'confirmPassword': 'Confirmer mot de passe',
    'passwordMatch': 'Les mots de passe ne correspondent pas',
    'phoneNumber': 'Numéro de téléphone',
    'birthDate': 'Date de naissance',
    'gender': 'Genre',
    'address': 'Adresse',
    'profession': 'Profession',
    'saveInfo': 'Sauvegarder les informations',
    'pleasePhoneNumber': 'Veuillez entrer le numéro de téléphone',
    'pleaseBirthDate': 'Veuillez entrer la date de naissance',
    'pleaseGender': 'Veuillez entrer le genre',
    'pleaseAddress': 'Veuillez entrer l\'adresse',
    'pleaseProfession': 'Veuillez entrer la profession',
    'passwordsDoNotMatch': 'Les mots de passe ne correspondent pas',
    'emailAlreadyUse':
        'L\'adresse e-mail est déjà utilisée par un autre compte',
    'additionalInfo': 'Informations supplémentaires',
    'male': 'Homme',
    'female': 'Femme',
    'alreadyHaveAnAccount': 'Vous avez déjà un compte ? Connexion',
    'passwordWeak': 'Le mot de passe est trop faible',
    'invalidEmailFormat': 'Format d\'email invalide',
    'tryAgain': "Veuillez réessayer",
    'Your_id_is_not_correct': 'Votre identifiant n\'est pas correct',
    'Your_secret_code_is_not_correct': 'Votre code secret n\'est pas correct',
    'Please_Enter_secret_code': 'Veuillez entrer le code secret',
    'ADMIN_PANEL': 'PANEL ADMIN',
    'Continue': 'Continuer',
    'Anthropometric_Information': 'Informations anthropométriques',
    'Cancel': 'Annuler',
    'Lesson': 'Leçon',
    'Step_1': 'Étape 1',
    'Please_enter': 'Veuillez entrer',
    'Step_2': 'Étape 2',
    'No_previous_records_found.': 'Aucun enregistrement précédent trouvé.',
    'Anthropometric_information_saved_successfully':
        'Informations anthropométriques enregistrées avec succès',
    'Error_saving_anthropometric_information':
        'Erreur lors de l\'enregistrement des informations anthropométriques',
    'Error_saving_anthropometric_information:':
        'Erreur lors de l\'enregistrement des informations anthropométriques :',
    'Error_fetching_anthropometric_data:':
        'Erreur lors de la récupération des données anthropométriques :',
    'Password_reset_email_sent_to':
        'E-mail de réinitialisation du mot de passe envoyé à',
    'Change_Password': 'Changer le mot de passe',
    'Recover_Password': 'Récupérer le mot de passe',
    'Password_Reset_Email_has_been_sent_!':
        'L\'e-mail de réinitialisation du mot de passe a été envoyé !',
    'No_user_found_for_that_email.':
        'Aucun utilisateur trouvé pour cet e-mail.',
    'Password_Recovery': 'Récupération de mot de passe',
    'Enter_your_mail': 'Entrez votre courriel',
    'Please_Enter_Email': 'Veuillez entrer votre adresse e-mail',
    'Send_Email': 'Envoyer un email',
    "Don't_have_an_account?": "Vous n'avez pas de compte ?",
    'Create': 'Créer',
    'User_Logged_In_Successfully': 'Utilisateur connecté avec succès',
    'No_User_Found_for_that_Email': 'Aucun utilisateur trouvé pour cet e-mail',
    'Wrong_Password_Provided_by_User':
        'Mot de passe incorrect fourni par l\'utilisateur',
    'Email_or_Password_is_Incorrect':
        'L\'e-mail ou le mot de passe est incorrect',
    'Please_Enter_Password': 'Veuillez entrer le mot de passe',
    "Don't_have_an_account?_Sign_up":
        "Vous n'avez pas de compte ? Inscrivez-vous",
    'receive_lesson_info': 'recevoir des informations sur la leçon',
    'Diagnosis_Results': 'Résultats du diagnostic',
    'Level_of_Gravity:': 'Niveau de gravité :',
    'Advices': 'Conseils',
    'Recommendation': 'Recommandation',
    'Close': 'Fermer',
    'Verify Phone Number': 'Vérifier le numéro de téléphone',
  };

  String? translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key];
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  @override
  bool isSupported(Locale locale) {
    return AppLocalizations._localizedValues.keys.contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

extension LocalizationExtension on BuildContext {
  String? translate(String key) {
    return AppLocalizations.of(this)?.translate(key);
  }
}
