// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDkVMGJb9qqgfIDrTZjX4OMtV92OXiiA',
    appId: '1:983425994049:web:5965a2baaee4f953d565c0',
    messagingSenderId: '983425994049',
    projectId: 'ecardio-v2-3bb56',
    authDomain: 'ecardio-v2-3bb56.firebaseapp.com',
    storageBucket: 'ecardio-v2-3bb56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQQwHFxBtdc233gFANIAkTEAFfFNhJLcs',
    appId: '1:983425994049:android:bb845d035dda42ead565c0',
    messagingSenderId: '983425994049',
    projectId: 'ecardio-v2-3bb56',
    storageBucket: 'ecardio-v2-3bb56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQ95EkabFRQfK05DTzIY4qnuxQdABifY',
    appId: '1:983425994049:ios:05f67665a7345eeed565c0',
    messagingSenderId: '983425994049',
    projectId: 'ecardio-v2-3bb56',
    storageBucket: 'ecardio-v2-3bb56.appspot.com',
    iosBundleId: 'com.example.ecardio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQ95EkabFRQfK05DTzIY4qnuxQdABifY',
    appId: '1:983425994049:ios:05f67665a7345eeed565c0',
    messagingSenderId: '983425994049',
    projectId: 'ecardio-v2-3bb56',
    storageBucket: 'ecardio-v2-3bb56.appspot.com',
    iosBundleId: 'com.example.ecardio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQDkVMGJb9qqgfIDrTZjX4OMtV92OXiiA',
    appId: '1:983425994049:web:e8e9a6de64cb7689d565c0',
    messagingSenderId: '983425994049',
    projectId: 'ecardio-v2-3bb56',
    authDomain: 'ecardio-v2-3bb56.firebaseapp.com',
    storageBucket: 'ecardio-v2-3bb56.appspot.com',
  );
}
